### ISSUE TITLE
Unsubscribing a topic subscription should unsubscribe everything from the topic

### ISSUE THREAD

**Issue by petemill** [deepstreamIO/deepstream.io-msg-redis#2]
Deepstream has some instances where it wants to unsubscribe a specific callback from being called for a topic. For example, when finished with an RPC Proxy call (after sending or receiving a response or error).

However, when MessageConnector.unsubscribe is called, passing through the appropriate callback, this connector unsubscribes everything from that topic with a blanket this.client.unsubscribe( topic );

I'm certain this isn't right, and is what is causing the issue I'm seeing at hoxton-one/deepstream.io#59

Could someone let me know if this is the case, and I suggest (I am happy to build it) creating an in-memory store of the topics we are still interested in, and the callback subscribers. When that reaches 0, then we can blanket unsubscribe from the topic. Furthermore, the subscription logic would also be faulty as we are subscribing multiple times. If this is the case, we should check if we are already subscribed first.

**Comment by WolframHempel** [comment]
Thank you very much for raising this. Using the test setup provided by @petemill (https://github.com/petemill/debug-issuereproduce-deepstream-distributedcalls) here's a log of the various subscriptions / unsubscriptions against the message connector.

![logging-subscribes](https://cloud.githubusercontent.com/assets/1503717/12165224/625009a4-b51c-11e5-9413-fd8db94e0701.png)
