### ISSUE TITLE
Upgrade ioredis to v3.0.0

### ISSUE THREAD

**Issue by rsignavong** [deepstreamIO/deepstream.io-msg-redis#48]
I would like to setup Deepstream in full HA setup and ensure there is no bugs left regarding Sentinel and failover as we regurlarly simulates server failure.

Moreover this version comes with a great improvement regarding the performance.
The interface is still the same so I don't think it will break the compatiblity with the usage of redis inside Deepstream.

Could you please upgrade the ioredis version to the last version v3.0.0?

**Comment by yasserf** [comment]
Done! Unfortunately we seemed to have dropped node 4 support, will be releasing a small patch and adding it back to CI as its not worth dropping support for small syntax improvements.
