### ISSUE TITLE
Version 0.2.7 that's in this repository and the one in npm differ

### ISSUE THREAD

**Issue by markomarkovic** [deepstreamIO/deepstream.io-msg-redis#7]
This is [deepstream.io-msg-redis-0.2.7.tgz](https://registry.npmjs.org/deepstream.io-msg-redis/-/deepstream.io-msg-redis-0.2.7.tgz) on npm. After unpacking it and comparing `package/package.json` with `package.json` from this repository, you'll notice that the dependencies differ, even though the version numbers are the same.

**Comment by yasserf** [comment]
Thanks for pointing this out. We released 0.2.9 that now resolves this issue
